drop table if exists users cascade;
create table users (
                      id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                      username varchar(255),
                      password varchar(255)
);