drop table if exists rule cascade;
create table rule (
                      id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                      device varchar(255),
                      browser varchar(255),
                      region varchar(255)
);

drop table if exists route_url cascade;
create table route_url (
                      id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
                      route_rule_id bigint,
                      destination_url varchar(255),
                      constraint fk_rule_route foreign key (route_rule_id) references rule (id)
);